### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by TCR-Reaper** [Auxilor/RarityDisplay#3]
**Describe the bug**
Rarity only displays up to 2 rarities for my server. For example, I have 4 current types (common, uncommon, rare, and very rare). But it will only display common and uncommon.

**To Reproduce**
Here is my config:
```
  - id: common
    items: [ ]
    display: "common"
  - id: uncommon
    items:
      - wooden_pickaxe
    display: "uncommon"
  - id: rare
    items:
      - stone_pickaxe
    display: "rare"
  - id: veryrare
    items:
      - iron_pickaxe
    display: "very rare"
```

**Expected behavior**
Each of those items, wooden, stone, and iron should have a different rarity, but they don't.

**Screenshots**
Images: 
https://prnt.sc/Ywfwa6leWawO
https://prnt.sc/_vPeeyRDUfKi
https://prnt.sc/crliOiKfkNoX

**Server Information (please complete the following information):**
This server is running Pufferfish version git-Pufferfish-44 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) 

Plugin Version: Latest

**Additional context**
None at the moment.
